# Generated by Django 2.1.1 on 2022-09-02 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('First_Clone_App', '0002_auto_20220902_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_dated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 9, 28, 25, 976783, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='create_dated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 9, 28, 25, 976116, tzinfo=utc)),
        ),
    ]
