# Generated by Django 2.1.1 on 2022-09-02 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('First_Clone_App', '0003_auto_20220902_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_dated',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 9, 29, 0, 79044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_dated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 9, 29, 0, 78039, tzinfo=utc)),
        ),
    ]
